In [ ]:
import random
import numpy as np
import secrets

# Example list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 1. Using random.choice()
single_random_element = random.choice(my_list)
print(f"Single random element using random.choice(): {single_random_element}")

# 2. Using random.choices()
multiple_random_elements_with_replacement = random.choices(my_list, k=3)
print(
    f"Multiple random elements with replacement using random.choices(): {multiple_random_elements_with_replacement}"
)

# 3. Using random.sample()
multiple_random_elements_without_replacement = random.sample(my_list, 3)
print(
    f"Multiple random elements without replacement using random.sample(): {multiple_random_elements_without_replacement}"
)

# 4. Using numpy.random.choice()
single_random_element_np = np.random.choice(my_list)
print(f"Single random element using numpy.random.choice(): {single_random_element_np}")

multiple_random_elements_np_with_replacement = np.random.choice(
    my_list, size=3, replace=True
)
print(
    f"Multiple random elements with replacement using numpy.random.choice(): {multiple_random_elements_np_with_replacement}"
)

multiple_random_elements_np_without_replacement = np.random.choice(
    my_list, size=3, replace=False
)
print(
    f"Multiple random elements without replacement using numpy.random.choice(): {multiple_random_elements_np_without_replacement}"
)

# 5. Using secrets.choice()
single_random_element_secure = secrets.choice(my_list)
print(f"Single random element using secrets.choice(): {single_random_element_secure}")

In [1]:
import numpy as np
from scipy.stats import multivariate_t

# Define the parameters of the multivariate t-distribution
mean = np.array([0, 0])  # Mean vector
scale_matrix = np.array([[1, 0.5], [0.5, 1]])  # Scale matrix (covariance matrix)
df = 5  # Degrees of freedom

# Generate random samples from the multivariate t-distribution
num_samples = 1000
samples = multivariate_t.rvs(loc=mean, shape=scale_matrix, df=df, size=num_samples)

print(f"Random samples from the multivariate t-distribution:\n{samples}")

# Calculate the PDF at a given point
point = np.array([0, 0])
pdf_value = multivariate_t.pdf(point, loc=mean, shape=scale_matrix, df=df)

print(f"PDF value at point {point}: {pdf_value}")

Random samples from the multivariate t-distribution:
[[-0.66775759 -3.30307101]
 [-1.31635278 -1.53097938]
 [ 0.38117213  1.64253909]
 ...
 [ 0.36587567 -0.07496254]
 [ 2.99936937  0.21230092]
 [ 0.75114847  0.47291609]]
PDF value at point [0 0]: 0.1837762984739307


In [179]:
import numpy as np
from scipy.stats import dirichlet
import heapq

# Define the concentration parameter vector
alpha = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# Generate random samples from the Dirichlet distribution
num_samples = 5
d = dirichlet(alpha)
samples = d.rvs(size=1)

print(f"Random samples from the Dirichlet distribution:\n{samples}")

k = 3

# Pair each element with its index and sort by the element in descending order
sorted_pairs = sorted(enumerate(samples[0]), key=lambda x: x[1], reverse=True)

# Extract the indices of the top-k elements
top_k_indices = [index for index, _ in sorted_pairs[:k]]
print(f"top {k} element indices: {top_k_indices}")

target_list = ["a", "b", "c", "d", "e", "f"]
# use the top_k_indices to extract the elements from target_list
top_k_elements = [target_list[i] for i in top_k_indices]
print(f"top {k} elements: {top_k_elements}")


# # Calculate the PDF at a given point
# point = np.array([0.2, 0.3, 0.5])
# pdf_value = dirichlet.pdf(point, alpha)

# print(f"PDF value at point {point}: {pdf_value}")

Random samples from the Dirichlet distribution:
[[0.21250854 0.04071029 0.10598189 0.55340819 0.08029092 0.00710017]]
top 3 element indices: [3, 0, 2]
top 3 elements: ['d', 'a', 'c']


In [39]:
import numpy as np
from scipy.stats import multinomial

# Parameters
n = 3  # Number of trials
p = [0.3, 0.3, 0.3]  # Probabilities of each category

# Generate a random sample
sample = multinomial.rvs(n, p, size=1)
print(f"Random sample from the multinomial distribution: {sample}")

# Calculate the probability of a specific outcome
outcome = [2, 3, 5]
probability = multinomial.pmf(outcome, n, p)
print(f"Probability of the outcome {outcome}: {probability}")

Random sample from the multinomial distribution: [[0 2 1]]
Probability of the outcome [2, 3, 5]: 0.0


In [156]:
import numpy as np
import random
from scipy.stats import multivariate_hypergeom

# Parameters
n_cov_symbols = 10
M = [n_cov_symbols] * n_cov_symbols  # Population sizes for each category
n = n_cov_symbols*2  # Number of draws

mh = multivariate_hypergeom(M, n)

# Generate a random sample
sample = mh.rvs(size=1)
print(f"Random sample from the multivariate hypergeometric distribution: {sample}")
print(random.randint(0, n_cov_symbols))

# Calculate the probability of a specific outcome
# outcome = [3, 5, 7]
# probability = multivariate_hypergeom.pmf(outcome, M, n)
# print(f"Probability of the outcome {outcome}: {probability}")

Random sample from the multivariate hypergeometric distribution: [[1 4 2 3 2 2 1 1 3 1]]
8


In [131]:
import numpy as np

# Parameters
lambda_ = [3, 4, 5]  # Mean rates for each category

# Generate random samples for each category
samples = [np.random.poisson(lam, size=1000) for lam in lambda_]

# Combine the samples into a multivariate sample
multivariate_samples = np.vstack(samples).T
print(
    f"Random samples from the multivariate Poisson distribution:\n{multivariate_samples[:5]}"
)

Random samples from the multivariate Poisson distribution:
[[3 3 4]
 [2 3 4]
 [3 2 5]
 [4 1 5]
 [5 2 7]]
